#!/bin/bash

curl https://www.archlinux.org/mirrorlist/all/ > /etc/pacman.d/mirrorlist.backup
sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.backup
echo 'put 10 fastest mirrors in /etc/pacman.d/mirrorlist'
rankmirrors -n 10 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
echo 'done'
